IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME='CUSTOMER' AND XTYPE='U')
	CREATE TABLE CUSTOMER (
		ID int NOT NULL PRIMARY KEY,
		FIRST_NAME nvarchar(250) NULL,
		LAST_NAME nvarchar(250) NULL,
		EMAIL varchar(250) NULL,
		COUNTRY varchar(100) NULL,
		APP_INSTALL bit default 0 NULL
	);